MyEvernote/ViewModels/InfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyEvernote.ViewModels
{
    public class InfoViewModel:NotifyViewModelBase<string>
    {
        public InfoViewModel()
        {
            Title = "Bilgilendirme";
        }
    }
}

MyEvernote/ViewModels/OkViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyEvernote.ViewModels
{
    public class OkViewModel:NotifyViewModelBase<string>
    {
        public OkViewModel()
        {
            Title = "İşlem Başarılı";

        }
    }
}

MyEvernote/ViewModels/WarningViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyEvernote.ViewModels
{
    public class WarningViewModel:NotifyViewModelBase<string>
    {
        public WarningViewModel()
        {
            Title = "Uyarı!";
        }
    }
}

MyEvernote/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyEvernote.BusinessLayer;
using MyEvernote.Entities;
using MyEvernote.Filters;
using MyEvernote.Models;

namespace MyEvernote.Controllers
{
    
    [Auth]
    [AuthAdmin]
    [Excp]
    public class CategoryController : Controller
    {

        private CategoryManager _categoryManager = new CategoryManager();

        public ActionResult Index()
        {

            return View(_categoryManager.List());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = _categoryManager.Find(x => x.Id == id.Value);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");
            if (ModelState.IsValid)
            {
               
                var result = _categoryManager.Insert(category);
                CacheHelper.RemoveCategoriesFromCache();/*Category tablosu değiştiği anda Cache'i 
                                                        temizliyoruz ve Cache'nin yeniden dolmasını sağlıyoruz*/
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            return View(category);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = _categoryManager.Find(x => x.Id == id.Value);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");
            if (ModelState.IsValid)
            {
                Category cat = _categoryManager.Find(x => x.Id == category.Id);
                cat.Title = category.Title;
                cat.Description = category.Description;
                var result = _categoryManager.Update(cat);
                CacheHelper.RemoveCategoriesFromCache();
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(category);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = _categoryManager.Find(x => x.Id == id.Value);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = _categoryManager.Find(x => x.Id == id);
            _categoryManager.Delete(category);
            CacheHelper.RemoveCategoriesFromCache();
            return RedirectToAction("Index");
        }
    }
}

MyEvernote/Controllers/EvernoteUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyEvernote.BusinessLayer;
using MyEvernote.BusinessLayer.Results;
using MyEvernote.Entities;
using MyEvernote.Filters;

namespace MyEvernote.Controllers
{
    [Auth]
    [AuthAdmin]
    [Excp]
    public class EvernoteUserController : Controller
    {

        private EvernoteUserManager _evernoteUserManager = new EvernoteUserManager();

        public ActionResult Index()
        {
            return View(_evernoteUserManager.List());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EvernoteUser evernoteUser = _evernoteUserManager.Find(x => x.Id == id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EvernoteUser evernoteUser)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");

            if (ModelState.IsValid)
            {
               
                BusinessLayerResult<EvernoteUser> result = _evernoteUserManager.Insert(evernoteUser);
                if (result.Errors.Count > 0)
                {
                    result.Errors.ForEach(x=>ModelState.AddModelError("",x.Message));
                    return View(evernoteUser);
                }
                return RedirectToAction("Index");
            }

            return View(evernoteUser);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EvernoteUser evernoteUser = _evernoteUserManager.Find(x => x.Id == id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EvernoteUser evernoteUser)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            ModelState.Remove("ModifiedUsername");
            if (ModelState.IsValid)
            {
               
                BusinessLayerResult<EvernoteUser> result = _evernoteUserManager.Update(evernoteUser);
                if (result.Errors.Count > 0)
                {
                    result.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(evernoteUser);
                }
                return RedirectToAction("Index");
            }
            return View(evernoteUser);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EvernoteUser evernoteUser = _evernoteUserManager.Find(x => x.Id == id.Value);
            if (evernoteUser == null)
            {
                return HttpNotFound();
            }
            return View(evernoteUser);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EvernoteUser evernoteUser = _evernoteUserManager.Find(x => x.Id == id);
            var result = _evernoteUserManager.Delete(evernoteUser);
            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

    }
}

MyEvernote/Views/Shared/Info.cshtml
@using MyEvernote.ViewModels
@model  InfoViewModel
@{
    ViewBag.Title = @Model.Title;
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-info text-center">@Model.Header</h4>
        </div>
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <span class="text-center"><i class="fas fa-info"></i></span><p>&nbsp;@Model.Title</p>
                <div class="text-justify">
                    @foreach (string msg in @Model.List)
                    {
                        <p class="text-info">@msg</p><br />
                    }

                </div>
            </div>
        </div>
    </div>

</div>

@{
    string js = string.Empty;
    js = " setTimeout(function() {window.location ='" + Model.RedirectingUrl + "';},'" + Model.RedirectingTimeOut + "');";
}

<script>

    $(function() {

        @Html.Raw(js);






    });


</script>

MyEvernote/Views/Shared/Ok.cshtml
@using MyEvernote.ViewModels
@model  OkViewModel
@{
    ViewBag.Title =@Model.Title;
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-success text-center">@Model.Header</h4>
        </div>
        <div class="col-md-12">
            <div class="alert alert-success" role="alert">
                <span class="text-center"><i class="fas fa-ok-circle"></i></span><p>&nbsp;@Model.Title</p>
                <div class="text-justify">
                    @foreach (string msg in @Model.List)
                    {
                        <p class="text-success">@msg</p><br />
                    }

                </div>
            </div>
        </div>
    </div>

</div>

@{
    string js = string.Empty;
    js = " setTimeout(function() {window.location ='" + Model.RedirectingUrl + "';},'" + Model.RedirectingTimeOut + "');";
}

<script>

    $(function() {

        @Html.Raw(js);






    });


</script>

MyEvernote/Views/Shared/Warning.cshtml
@using MyEvernote.ViewModels
@model  WarningViewModel
@{
    ViewBag.Title = @Model.Title;
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-warning text-center">@Model.Header</h4>
        </div>
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert">
                <span class="text-center"><i class="fas fa-ok-exclamation"></i></span><p>&nbsp;@Model.Title</p>
                <div class="text-justify">
                    @foreach (string msg in @Model.List)
                    {
                        <p class="text-warning">@msg</p><br />
                    }

                </div>
            </div>
        </div>
    </div>

</div>

@{
    string js = string.Empty;
    js = " setTimeout(function() {window.location ='" + Model.RedirectingUrl + "';},'" + Model.RedirectingTimeOut + "');";
}

<script>

    $(function() {

        @Html.Raw(js);
        

    });


</script>

MyEvernote/Views/Shared/_Layout.cshtml
@using MyEvernote.Entities
@using MyEvernote.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Myevernote-@ViewBag.Title</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menü</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">My Evernote</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @if (CurrentSession.User != null)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-wrench">&nbsp;</span>Yönetim <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Create","Note")"><span class="glyphicon glyphicon-plus">&nbsp;</span>Not Ekle</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index","Note")"><span class="glyphicon glyphicon-th-list">&nbsp;</span>Notlarım</a></li>
                                <li><a href="@Url.Action("MyLikedNotes","Note")"><span class="glyphicon glyphicon-heart">&nbsp;</span>Beğendiklerim</a></li>
                                @if (CurrentSession.User.isAdmin)
                                {
                                    <li role="separator" class="divider"></li>
                                    @*<li>@Bootstrap.LinkMenu("/Category/Create","plus", "Kategori Ekle", "")</li> //Helper Metodumuzlada link verebiliriz*@
                                    <li><a href="@Url.Action("Create","Category")"><span class="glyphicon glyphicon-plus">&nbsp;</span>Kategori Ekle</a></li>
                                    <li><a href="@Url.Action("Index","Category")"><span class="glyphicon glyphicon-th-list">&nbsp;</span>Kategoriler</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="@Url.Action("Create","EvernoteUser")"><span class="glyphicon glyphicon-plus">&nbsp;</span>Kullanıcı Ekle</a></li>
                                    <li><a href="@Url.Action("Index","EvernoteUser")"><span class="glyphicon glyphicon-user">&nbsp;</span>Kullanıcılar</a></li>
                                }
                            </ul>
                        </li>
                    }
                    <li>
                        <a href="@Url.Action("MostLiked", "Home")">
                            <span class="glyphicon glyphicon-star"></span> En Beğenilenler
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <span class="glyphicon glyphicon-th-list"></span> Son Yazılanlar
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("About", "Home")">
                            <span class="glyphicon glyphicon-info-sign"></span> Hakkımızda
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (CurrentSession.User == null)
                    {
                        <li>
                            <a href="@Url.Action("Register", "Home")"> <span class="glyphicon glyphicon-user"></span> Üye Ol</a>
                        </li>
                        <li>

                            <a href="@Url.Action("Login", "Home")">
                                <span class="glyphicon glyphicon-log-in"></span> Giriş
                            </a>
                        </li>
                    }
                    else
                    {

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> @CurrentSession.User.UserName <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("ShowProfile","Home")"><span class="glyphicon glyphicon-eye-open">&nbsp;</span>Profili Görüntüle</a> </li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("EditProfile","Home")"><span class="glyphicon glyphicon-edit">&nbsp;</span>Düzenle</a></li>
                                <li><a href="@Url.Action("RemoveProfile","Home")" onclick="return confirm('Hesabınızı Silmek istediğinize emin misiniz?');"><span class="glyphicon glyphicon-trash">&nbsp;</span>Sil</a></li>

                            </ul>
                        </li>

                        <li>
                            <a href="@Url.Action("Logout", "Home")">
                                <span class="glyphicon glyphicon-log-out"></span> Çıkış
                            </a>
                        </li>
                    }
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        @RenderBody()
    </div>
    <hr />
    <!-- /.container -->
    <div class="container">
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-4 text-center">
                    <strong class="text-info">Site Haritası</strong><hr />
                    <a href="#"><span class="glyphicon glyphicon-info-sign"></span> Hakkımızda</a><br /><br />
                    <a href="#"><span class="glyphicon glyphicon-star"></span> En Beğenilenler</a><br /><br />
                    <a href="#"><span class="glyphicon glyphicon-th-list"></span> Son Yazılanlar</a><br /><br />
                </div>

                <div class="col-lg-4 text-center">
                    <strong class="text-center text-info">MyEvernote</strong><hr />
                    <p class="text-info">Tüm Hakları Saklıdır &copy; MyEvernote @DateTime.Now.Year</p>
                </div>

                <div class="col-lg-4 text-center">
                    <strong class="text-center text-info">E-Bülten Üyeliği</strong><hr />
                    <p class="text-info"> Consectetur adipiscing elit fusce vel.</p>

                    <div class="row">
                        <div class="col-md-10">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="E-posta adresiniz">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button"><span class="glyphicon glyphicon-send"></span> Gönder</button>
                                </span>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->

</body>
</html>

MyEvernote/Views/Shared/_LayoutAccount.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <!--Made with love by Mutiullah Samim -->
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!--Custom styles-->

    <link href="~/Content/Login-Register.css" rel="stylesheet" />
    @RenderSection("Head", false)
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">@ViewBag.Title</h3>
                    @RenderSection("Social", false)
                </div>
                <div class="card-body">
                    @RenderBody()
                </div>
                @RenderSection("Footer", false)
            </div>
        </div>
    </div>
</body>
</html>

MyEvernote/Views/Shared/_PartialCategories.cshtml
@using MyEvernote.BusinessLayer
@using MyEvernote.Entities
@using MyEvernote.Models

@{

    List<Category> liste = CacheHelper.GetCategoryFromCache();
}


<div class="list-group ">
    <a href="@Url.Action("Index","Home")" class="list-group-item active" style="background-color: #262626; border: #262626;">Tüm Kategoriler</a>
    @foreach (Category category in liste)
    {
        <a href="@Url.Action("Select","Home",new {id=category.Id})" title="@category.Description" class="list-group-item"><span class="glyphicon glyphicon-arrow-right"></span> @category.Title</a>

    }
   
</div>

MyEvernote/Views/Shared/_PartialComments.cshtml
@using MyEvernote.Models
@model List<Comment>

@{
    EvernoteUser user = CurrentSession.User;
}

@foreach (Comment comment in Model)
{
    <div class="media">
        <div class="media-left media-top">
            <div class="media-object">
                <span class="glyphicon glyphicon-comment"></span>
            </div>
        </div>

        <div class="media-body">
            <div>
                <div class="col-md-12">
                    <small class="mt-0"><span class="glyphicon glyphicon-user"></span> @comment.Owner.UserName</small>&nbsp;&nbsp;
                    <small class="mt-0"><span class="glyphicon glyphicon-time"></span> @comment.ModifiedOn</small>
                </div>
                <br />
                <div class="col-md-10" id="comment_text_@comment.Id" contenteditable="false">
                    @comment.Text
                </div>
                @if (user != null && comment.Owner.Id == user.Id)
                {
                    <div class="col-md-2">
                        <button type="button" class="btn btn-warning btn-xs" data-edit-mode="false" onclick="doComment(this,'edit_clicked',@comment.Id,'#comment_text_@comment.Id');"><span class="glyphicon glyphicon-edit"></span></button>
                        <button type="button" class="btn btn-danger btn-xs" data-edit-mode="false" onclick="doComment(this,'delete_clicked',@comment.Id);"><span class="glyphicon glyphicon-trash"></span></button>
                    </div>
                }
            </div>
        </div>
    </div>
}
@if (user != null)
{
    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="float-right">
            <div class="col-lg-8">
                <div class="input-group">
                    <input type="text" id="new_comment_text" class="form-control" placeholder="Yorumunuz..">
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="button" onclick="doComment(this,'new_clicked',-1);"><span class="glyphicon glyphicon-send"></span> Gönder</button>
                    </span>
                </div>
            </div>
        </div>
    </div>

}

MyEvernote/Views/Shared/_PartialNoteText.cshtml
@model Note


<div class="row">
    <div class="col-md-12">
        <h3 class="text-center text-muted">@Model.Title</h3>
    </div>
    <div class="col-md-12">
        <hr />
    </div>
    <div class="col-md-12">
        <p class="text-justify">
            @Model.Text 
        </p>
    </div>
    <div class="col-lg-5 pull-right">
        <span class="glyphicon glyphicon-user"></span> @Model.Owner.UserName&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-time"></span> @Model.ModifiedOn
    </div>
</div>